env:
  RELEASE_NAME: JS Engine - ${{ github.event.inputs.tag_name }} Release

jobs:
  ensure-tag:
    name: Create Tag (if needed)
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.pre_changelog_message.outputs.body }}
    steps:
      - uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Create and push tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag "${{ github.event.inputs.tag_name }}"
          git push origin "${{ github.event.inputs.tag_name }}"

      - name: Prepare pre-changelog message
        id: pre_changelog_message
        run: |
          BODY=""
          if [ -n "${{ github.event.inputs.custom_message }}" ]; then
            BODY="${{ github.event.inputs.custom_message }}"
          fi

          {
            echo "body<<EOF"
            printf '%s\n' "$BODY"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  release-linux:
    needs: [build, ensure-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linuxBuild
          path: build

      - run: |
          sudo apt-get install -y p7zip-full
          7z a -tzip linuxBuild.zip ./build/*

      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag_name }}
          release_name: ${{ env.RELEASE_NAME }}
          file: linuxBuild.zip
          asset_name: FNF-JS-Engine-linux.zip
          prerelease: ${{ github.event.inputs.prerelease }}
          body: ${{ needs.ensure-tag.outputs.body }}
          overwrite: true
